### PR TITLE
Added support for a :second option in the cron map. Cron maps without th...

### PR DESCRIPTION
**Pull request by reifytech**
...e :second option will work as before. Added new tests

### CODE REVIEW

**Comment by AdamClements** [comment]
Hi, first of all thanks for the contribution! 

What is your use case for wanting to the second scheduling? I thought about this when writing the library originally and came to the conclusion that anyone scheduling anything more fine grained than per minute would probably want a different library oriented around timers and fixed delays (say, at-at) rather than cron style days/months etc. 

My only concern with this change is efficiency. I know it's not doing much every second, but once per minute seemed like a much safer bet for not accidentally missing some timer calls with long running tasks that haven't been wrapped in a future.  And if you're using the library to fire once per day or week, it feels like pretty major overkill to be checking once per second. 

So like I say, I'd be interested to hear your use case, and if this library really is the right fit for the task, perhaps we could add a little extra code to your pull request to make it only check once per <minimum time difference>

**Comment by AdamClements** [comment]
Oh and the other minor concern is simply one of symmetry/consistency in that the default is to run every minute of every day of everything month... etc. And then narrow that in your cron map. This changes that for seconds, fairly reasonably, it would be awkward to have a default run every second, especially as that would change existing behaviour.. I'm not sure there's a satisfactory solution to this though. It's a fairly minor concern.

**Comment by reifytech** [comment]
Hi Adam -

Thanks for replying. I had not come across at-at before - that satisfies
90% of what I need.

I use the (Java) Quartz library for all scheduled tasks included stuff that
runs every 5 seconds for example - things like moving data from temporary
storage, 3rd party monitoring, etc.

You are right, fitting this into your library does not seem correct,
especially when a specialized library is available.

Thanks for the library - I was wrestling with Quartzite until I came across
yours. This library makes things much simpler (and much less "enterprisey")

Thanks
Raja

**Comment by AdamClements** [comment]
Going to close this now if you're satisfied with my answer.

I might transcribe some of this conversation into the README for anyone else who comes to this library with the same needs as you.

Thanks again for the contribution :)

**Comment by reifytech** [comment]
Adam - Sorry about the late reply - just saw that you've closed this.

Again, thanks for the library!

**Pull request closed without merging**
